import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer';
import { ContextProvider } from '@/lib/context/ContextProvider';
import Trash from '@/components/Section/Gallery/Trash';
import Error from '@/components/Section/Gallery/Trash';
import LenisScroll from '@/lib/context/LenisScroll';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				suppressHydrationWarning={true}
				className={`${inter.className}`}>
				<ContextProvider>
					<LenisScroll />
					<Error>
						<Navbar />
						{children}
					</Error>
				</ContextProvider>
			</body>
		</html>
	);
}
